
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import AaveBridgeContractArtifactJson from '../aave_bridge/target/aave_bridge_contract-AaveBridge.json' with { type: 'json' };
export const AaveBridgeContractArtifact = loadContractArtifact(AaveBridgeContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract AaveBridge;
 */
export class AaveBridgeContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, AaveBridgeContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): AaveBridgeContract {
    return Contract.at(address, AaveBridgeContract.artifact, wallet) as AaveBridgeContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, token: AztecAddressLike, portal: EthAddressLike) {
    return new DeployMethod<AaveBridgeContract>(PublicKeys.default(), wallet, AaveBridgeContractArtifact, (instance, wallet) => AaveBridgeContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, token: AztecAddressLike, portal: EthAddressLike) {
    return new DeployMethod<AaveBridgeContract>(publicKeys, wallet, AaveBridgeContractArtifact, (instance, wallet) => AaveBridgeContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AaveBridgeContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<AaveBridgeContract['methods'][M]>
  ) {
    return new DeployMethod<AaveBridgeContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      AaveBridgeContractArtifact,
      (instance, wallet) => AaveBridgeContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AaveBridgeContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(AaveBridgeContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config'> {
      return {
        config: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'config'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** claim_private(recipient: struct, amount: integer, secret_for_L1_to_L2_message_consumption: field, message_leaf_index: field) */
    claim_private: ((recipient: AztecAddressLike, amount: (bigint | number), secret_for_L1_to_L2_message_consumption: FieldLike, message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_public(to: struct, amount: integer, secret: field, message_leaf_index: field) */
    claim_public: ((to: AztecAddressLike, amount: (bigint | number), secret: FieldLike, message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(token: struct, portal: struct) */
    constructor: ((token: AztecAddressLike, portal: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** exit_to_l1_private(token: struct, recipient: struct, amount: integer, caller_on_l1: struct, authwit_nonce: field) */
    exit_to_l1_private: ((token: AztecAddressLike, recipient: EthAddressLike, amount: (bigint | number), caller_on_l1: EthAddressLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** exit_to_l1_public(recipient: struct, amount: integer, caller_on_l1: struct, authwit_nonce: field) */
    exit_to_l1_public: ((recipient: EthAddressLike, amount: (bigint | number), caller_on_l1: EthAddressLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
